### ISSUE TITLE
Get-IdentityNowTransform does not return list of transforms when back slashes are included in a transform

### ISSUE THREAD

**Issue by bama19942000** [darrenjrobinson/powershell_module_identitynow#11]
This cmdlet does not seem to return a list of transforms when you have a transform in the list that has a backslash(s) in it- ( a transform that uses velocity scripting with backslashes for example). The JSON object is being populated with escape characters everywhere which prevent the code from traversing the object for id.

**Comment by darrenjrobinson** [comment]
Can you please provide me with an example transform so I can test with?

**Comment by bama19942000** [comment]
It is not the backslashes. In my sandbox environment I removed each transform one at a time until I found the bad apple.

{
            "attributes": {
                "input": {
                    "attributes": {
                        "values": [
                            {
                                "attributes": {
                                    "name": "zlastcharacterofuid"
                                },
                                "type": "identityAttribute"
                            },
                            {
                                "table": {
                                    "O": "LAST LETTER O",
                                    "default": "DEFAULT",
                                    "o": "LAST LETTER O"
                                }
                            }
                        ]
                    },
                    "type": "lookup"
                }
            },
            "id": "bad apple",
            "type": "tolower"
        },

Matt Totty | Principal Consultant, IAM
m. 205.215.4062

**Comment by darrenjrobinson** [comment]
Yes, it looks like this isn't valid

                        "table": {
                            "O": "LAST LETTER O",
                            "default": "DEFAULT",
                            "o": "LAST LETTER O"
                        }

Cannot convert the JSON string because a dictionary that was converted from the string
contains the duplicated keys 'O' and 'o'.

**Comment by bama19942000** [comment]
The transform itself in IDN is valid. Anytime we have a lookup table like that convert to json seems to insert escape characters everywhere in an attempt to distinguish the keys. Even though json is case sensitive power shell is not. So i believe that is what is going on.

Sent from my iPhone

On Feb 18, 2020, at 8:27 PM, Darren Robinson <notifications@github.com<mailto:notifications@github.com>> wrote:

[External Email]
________________________________

Yes, it looks like this isn't valid

                    "table": {
                        "O": "LAST LETTER O",
                        "default": "DEFAULT",
                        "o": "LAST LETTER O"
                    }


Cannot convert the JSON string because a dictionary that was converted from the string
contains the duplicated keys 'O' and 'o'.

**Comment by darrenjrobinson** [comment]
The update I just pushed will now return all transforms.
You will still have issues with duplicate keys if you try and convert a transform that contains two keys with the same name (PowerShell doesn't respect case, so O and o are seen as duplicates).

To overcome that try this;

```
$xForms = Get-IdentityNowTransform
[void][System.Reflection.Assembly]::LoadWithPartialName("System.Web.Extensions") 
$idnObj = (New-Object -TypeName System.Web.Script.Serialization.JavaScriptSerializer -Property @{MaxJsonLength=67108864}).DeserializeObject($xForms) 
$idnObj.items
```

**Comment by bama19942000** [comment]
Thanks Darren, I will try it out!

Matt…

Matt Totty | Principal Consultant, IAM
m. 205.215.4062
