### ISSUE TITLE
Can you add the -json switch to the Invoke-IdentityNowRequest

### ISSUE THREAD

**Issue by bama19942000** [darrenjrobinson/powershell_module_identitynow#17]
When returning data from the beta/sources API call, for example, a certain configuration for one of the connectors, which I have not identified as there are many, is inserting escape characters just as it was for the transforms. If we could get the -json switch added to this cmdlet, then it would make it much easier to grab and parse data for various subsequent operations.

**Comment by darrenjrobinson** [comment]
Sounds like a good idea. Will do.

**Comment by darrenjrobinson** [comment]
Updates included in release 1.1.0
