### ISSUE TITLE
Get-IdentityNowSourceAccounts does not include attributes

### ISSUE THREAD

**Issue by 410sean** [darrenjrobinson/powershell_module_identitynow#2]
Get-IdentityNowSourceAccounts does not include attributes

this is due to v2 API requiring a single account query to get attributes

**Comment by darrenjrobinson** [comment]
Yes, Get-IdentityNowSourceAccounts is using the v2 Accounts API to retrieve all accounts on a source. 

Does this give you want you are looking for?
```
$source = Get-IdentityNowSourceAccounts 12345 
foreach ($account in $source) {
    $accountDetails = Search-IdentityNowUsers -query $account.identity.id 
    $accountDetails.attributes
}
```

**Comment by 410sean** [comment]
it does for a little bit, i was testing adding an $attributes switch and before the return of get-identitysourceaccounts adding the following code
`if ($attributes){
                $temp=$sourceObjects
                $sourceObjects=@()
                $i=0
                foreach ($Object in $temp){
                    $i++
                    Write-Progress -Activity "fetching account attributes $($i) of $($temp.count)" -PercentComplete ($i/$temp.count*100)
                    $result=Invoke-RestMethod -Method Get -Uri "https://$($IdentityNowConfiguration.orgName).api.identitynow.com/v2/accounts/$($object.id)" -Headers $Headersv2      
                    $sourceObjects+=$result
                }
            }`

what you provided was working but eventually the v3 token expired so trying to see how to auto renew.

**Comment by darrenjrobinson** [comment]
Yes the token life is limited (~12 mins from memory).
You can inspect the token expiry using [this module](https://github.com/darrenjrobinson/JWTDetails) I wrote recently.

**Comment by 410sean** [comment]
resolved with update to add -attributes switch or looping command
