### ISSUE TITLE
"Get-IdentityNowTransform -ID $name" does not return a result

### ISSUE THREAD

**Issue by 410sean** [darrenjrobinson/powershell_module_identitynow#25]
when running Get-IdentityNowTransform and specifying a transform name, no result will be returned

**Comment by 410sean** [comment]
i can't seem to submit a new pull request with one still active. i have the fix for this and a new function in the following commit:
https://github.com/darrenjrobinson/powershell_module_identitynow/commit/43583d9111cde0cbf2c1df364aa84570bd36ef53

**Comment by darrenjrobinson** [comment]
Updated in https://github.com/darrenjrobinson/powershell_module_identitynow/pull/30
