### ISSUE TITLE
Unable to generate V2 Keys anymore using New-IdentityNowAPIClient

### ISSUE THREAD

**Issue by bama19942000** [darrenjrobinson/powershell_module_identitynow#26]
An issue related to generating the v2 keys. This seems to be happening all the time now. Something must have changed on the sailpoint side. Here is the error when executing the command.
New-IdentityNowAPIClient : Create API Client failed. {
   "msg_template": "Oathkeeper clients must be VA clients",
   "slpt_error_code": "SLPT-1006",
   "formatted_msg": "(SLPT-1006) Oathkeeper clients must be VA clients",
   "exception_id": "173BF751D57",
   "error_code": 1006,
   "exception_class": "com.cloudmasons.exceptions.SLPTInvalidStateException",
   "exception_detail": {
      "file": "ClientService.groovy",
      "method": "createClient",
      "line_number": 632,
      "class": "com.cloudmasons.ClientService"
   },
   "http_response_code": 400,
   "timestamp": "2020-08-05 16:29:50.295",
   "exception_message": "(SLPT-1006) Oathkeeper clients must be VA clients"
}
At line:1 char:1
+ New-IdentityNowAPIClient
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-IdentityNowAPIClient

**Comment by darrenjrobinson** [comment]
Thx for submitting. I've been able to replicate it. 
Seems SailPoint are restricting the generation of V2 Credentials solely for VA's. 

The API endpoint has also been updated, and v2 credential creation must now specify a **VALID** VA Cluster to be associated with.  
Whilst I've validated with these changes v2 credentials can be generated (spoofing a new non existent VA associated with a VA cluster) this is very much against the intent of deprecating v2 creds. 

I'll need to go through and see what API's the module is using V2 creds for, see if those API's are now accepting Personal Access Tokens and update accordingly. 

FWIW with a few changes here is generating v2 Creds adhering to the new constraints. 

![image](https://user-images.githubusercontent.com/384733/89469789-8f3aaf00-d7bd-11ea-8e31-c0e5c1f2fcbe.png)

**Comment by darrenjrobinson** [comment]
Updated New-IdentityNowAPIClient cmdlet will be included in v1.1.2.

**Comment by justinhaines** [comment]
Hi Darren, just to confirm - we need to wait until v1.1.2 to be released in order to generate the V2 creds, is that correct? Thanks as always!

**Comment by darrenjrobinson** [comment]
The code is checked in, but yes will be released in v1.1.2 of the module next week.
If you need it ASAP you can download the updated cmdlet (New-IdentityNowAPIClient.ps1 from the [v1.1.2 branch](https://github.com/darrenjrobinson/powershell_module_identitynow/tree/v1.1.2)) scripts directory and drop it in the \scripts folder where you have the Module installed and it will work.

**Note** v2 API Clients can now only be created when assigned to a VA Cluster. New-IdentityNowAPIClient now has the required -clusterId parameter to specify the VA Cluster to create the VA Client (v2 Auth) for.

**Comment by darrenjrobinson** [comment]
Updated in https://github.com/darrenjrobinson/powershell_module_identitynow/pull/30
