### ISSUE TITLE
"The term 'Get-Hash' is not recognized as..." when running cmdlets

### ISSUE THREAD

**Issue by demongp** [darrenjrobinson/powershell_module_identitynow#3]
I have setup the configuration as far as I could, from your excellent blog posts.

When I try to run something like Get-IdentityNowRule or  Get-IdentityNowRole, I get a failure on "get-hash", indicating that my system does not have it.

I don't find any information on this being a default cmdlet in PS.  This is my version of PS

> Name                           Value
> ----                           -----
> PSVersion                      5.1.18362.145
> PSEdition                      Desktop
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
> BuildVersion                   10.0.18362.145
> CLRVersion                     4.0.30319.42000
> WSManStackVersion              3.0
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1

**Comment by darrenjrobinson** [comment]
The SailPointIdentityNow PowerShell Module has a dependency on the PowerShell Community Extensions module. 
Both the Installer and the Module Import scripts look to fulfil this. 

Sounds like you need to perform the install manually. 

From an elevated PowerShell session execute the following
```
Install-Module -Name Pscx -RequiredVersion 3.3.2 -Force -AllowClobber -scope AllUsers
```

**Comment by demongp** [comment]
Thanks Darren.  I missed that part in the repo wiki
