### ISSUE TITLE
Search AccountActivities

### ISSUE THREAD

**Issue by justinhaines** [darrenjrobinson/powershell_module_identitynow#34]
Similar to Search-IdentityEvents, it would be great to have Search-AccountActivities. The API is the same but the indices is "accountactivities" and it provides more fine grained information than the /account-activities API. Or is it possible to use one of the existing? Thanks!

**Comment by darrenjrobinson** [comment]
There is the Get-IdentityNowAccountActivities cmdlet that does this from a user/account perspective. Does that provide the details you're looking for?

Checkout the Account Activities section in the doco here https://gist.github.com/darrenjrobinson/dfbf7470212fb295fc13c6608d91c0f1 for examples of what is available.

**Comment by justinhaines** [comment]
Hi Darren--

The Account Activities API doesn't provide details that the Search API
(with indices "accountactivities") provides. For example, I am looking for
the email address for newly created accounts. Using Postman and the Search
API, I can get those details but with the Account Activities, I cannot (as
far as I know!).

Thanks!

**Comment by darrenjrobinson** [comment]
Addressed in this commit. 
New cmdlet for Search-IdentityNow that allows indice to be specified. 
https://github.com/darrenjrobinson/powershell_module_identitynow/pull/38/commits/72433db4219c288a08ba36feeddb7cbee0d3e109 

Will be avail in v1.1.4 shortly.
