### ISSUE TITLE
Documentation not correct

### ISSUE THREAD

**Issue by dreic** [darrenjrobinson/powershell_module_identitynow#35]
Hello, 

in [documentation ](https://github.com/darrenjrobinson/powershell_module_identitynow#setting-up-credentials-and-organisation-configuration) 1 step is missing.

After ` $v3Creds = [pscredential]::new($clientIDv3, ($clientSecretv3 | ConvertTo-SecureString -AsPlainText -Force))` you need to add `Set-IdentityNowCredential -AdminCredential $adminCreds -v3APIKey $v3Creds` to be able to run `$personalAccessToken = New-IdentityNowPersonalAccessToken -name "IDN Automation" `.  You get an error about wrong admin credentials and v3 api.

**Comment by darrenjrobinson** [comment]
Thx for letting me know. Corrected.
