### ISSUE TITLE
idnV3 referenced but not declared in Get-IdentityNowCertCampaignReport

### ISSUE THREAD

**Issue by 1-one** [darrenjrobinson/powershell_module_identitynow#36]
Hi,

I've been trying to use Get-IdentityNowCertCampaignReport but it breaks on $accesst = $IDNv3.headers.authorization.split(" ")  as there is no declaration of $IDNv3 and I can't work out where to get the $taccess from for the urlsignature. Basically, if I use $v3Token.access_token I get a 404 off of report/get... Now, I know I can call getReports as a Beta API now and that worsk fine for me but I can't actually pull down the report without report/get from the provate API's as you use it... but it doesn't work because of the $IDNv3 reference.
Any ideas please? Is this a bug or, as I suspect, am I an idiot?
Thanks
Julian

**Comment by 1-one** [comment]
Oh, I can't believe I forgot to say:
Thanks so much for this amazing work. You have saved me so much pain when it comes to writing API code for IDN. I can't tell you how much I appreciate it!!
Cheers
Julian

**Comment by darrenjrobinson** [comment]
What version of the IDN PowerShell Module are you using? $IDNv3 sounds like one of the original releases (such as v1.0.2) https://www.powershellgallery.com/packages/SailPointIdentityNow/1.0.2/Content/scripts%5CGet-IdentityNowCertCampaignReport.ps1 
The later versions use the modern authentication changes for the IDN API's and all the fudgery I used to have to do is gone. 
Try using v1.1.3 https://www.powershellgallery.com/packages/SailPointIdentityNow/1.1.3 

DR

**Comment by 1-one** [comment]
Hi,

Sorry for the delay, I've been on a deadline. Anyway, I just ran a clean install and pulled

$accesst = $IDNv3.headers.authorization.split(" ") 

From Get-IdentityNowCertcampaignreport.ps1 from ver 1.1.3 IE the path is C:\Users\MyUserName\Documents\WindowsPowerShell\Modules\SailPointIdentityNow\1.1.3\scripts

$IDNv3 is not declared or populated anywhere. Further I don't know where else to get the url_signature from as in

` $reportDetails = Invoke-RestMethod -Method Get -Uri "https://$($IdentityNowConfiguration.orgName).api.identitynow.com/cc/api/report/get/$($report.taskResultId)?format=csv&name=Export+Campaign+Status+Report&url_signature=$($accesst[1])" -Headers @{Authorization = "$($v3Token.token_type) $($v3Token.access_token)" }                                    
` 
Thanks
Julian

**Comment by darrenjrobinson** [comment]
It would seem that you have two versions of the module installed. You can see the v1.1.3 version under the personal module path, but I'd imagine their is an earlier version somewhere Globally like C:\Program Files\WindowsPowerShell\Modules 
Check there and remove the old version and try again.
