### ISSUE TITLE
Trouble with Auth into Sailpoint

### ISSUE THREAD

**Issue by jiggle-1** [darrenjrobinson/powershell_module_identitynow#37]
Hey Darren -

Thanks for all of your work on this project. We appreciate it.

I am having trouble authenticating and I've tried everything that I can think of. Would you mind taking a look at these errors? It's failing in both Dev and Prod. A previous release of your module did work. I have checked my creds many times and they *should* be good. I am able to see that I am hitting the right Sailpoint accounts but still no joy. I did find a older version of the module that is not cleaned up.

Invoke-RestMethod : {"error":"invalid_grant","error_description":"Bad Credentials"}
At C:\Users\******\Documents\WindowsPowerShell\Modules\SailPointIdentityNow\1.1.3\scripts\Get-IdentityNowAuth.ps1:237 
char:20
+ ...  $v3Token = Invoke-RestMethod -Uri $oAuthURI -Method Post -Body $oAut ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException   
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Write-Verbose : Cannot bind argument to parameter 'Message' because it is null.
At C:\Users\******\Documents\WindowsPowerShell\Modules\SailPointIdentityNow\1.1.3\scripts\Get-IdentityNowAuth.ps1:266 
char:27
+             Write-Verbose $v3Token
+                           ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Verbose], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.WriteVerboseComman  
   d

Write-Verbose : Cannot bind argument to parameter 'Message' because it is null.
At C:\Users\********\Documents\WindowsPowerShell\Modules\SailPointIdentityNow\1.1.3\scripts\Get-IdentityNowAuth.ps1:273 
char:19
+     Write-Verbose $requestHeaders
+                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Verbose], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.WriteVerboseComman  
   d

New-IdentityNowPersonalAccessToken : Authentication Failed. Check your AdminCredential and v3 API ClientID and ClientSecret. 
At line:16 char:24
+ ... cessToken = New-IdentityNowPersonalAccessToken -name "IDN Automation" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-IdentityNowPersonalAccessToken

ConvertTo-SecureString : Cannot bind argument to parameter 'String' because it is null.
At line:17 char:94
+ ... onalAccessToken.secret | ConvertTo-SecureString -AsPlainText -Force))
+                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertTo-SecureString], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertToSecureStr 
   ingCommand

Exception calling ".ctor" with "2" argument(s): "Cannot process argument because the value of argument "userName" is not 
valid. Change the value of the "userName" argument and run the operation again."
At line:17 char:36
+ $patCreds = [pscredential]::new("$($personalAccessToken.id)", ($perso ...
+                                    ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : PSArgumentException

Thanks again

**Comment by darrenjrobinson** [comment]
Hi @jiggle-1 
Looks like you are using the latest version (1.1.3). 
My only thought (other than incorrect creds for an environment) is your configuration file has gotten messed up moving between versions of the module.

In File Explorer navigate to your %localappdata% path and find the IdentityNowConfiguration.clixml file and rename it / delete it. 
Then setup your environments and credential configuration again as per the latest process https://github.com/darrenjrobinson/powershell_module_identitynow#setting-up-credentials-and-organisation-configuration 

DR

**Comment by 410sean** [comment]
Get-IdentityNowAuth -Verbose may help with troubleshooting auth, you can see if the first line is 
VERBOSE: AuthType: Personal Access Token
or
VERBOSE: AuthType: Admin Creds

its hard to tell but you may be trying to use PAT, you can get a new token from here if it helps but i agree maybe reentering the creds should help
https://{orgname}.identitynow.com/ui/d/user-preferences/personal-access-tokens

**Comment by darrenjrobinson** [comment]
If you go the path of reconfiguring your creds restart the module after removing the old configuration file so you’re starting with an empty config profile.

**Comment by jiggle-1** [comment]
Thanks for the quick response and the suggestions. 

Unfortunately, no dice with regenerating the clixml file. I tested in both SB and Prod. FYI this worked fine back in Dec. I'm pretty sure I'm using the same module, but I cleared it and reimported just in case. My account password in SB does look questionable based on how it aggregated. I do see auth attempts failing against an sailpoint SB user account that I expect.

My account in prod looks fine so the password shouldnt be an issue. I'm working on confirming. I did process an password reset today with the hopes of proving that prod Sailpoint and I agree on the password. 

I have regenerated API keys a few times today and I'm sure I havent mixed those up every time (probably at least once though). I did try various combinations of private vs system api keys with no joy.

I do have the feeling this is on our side.

Are passwords required if I have an API key? I'm thinking I should try testing something more stripped down (postman).

**Comment by darrenjrobinson** [comment]
Step through one at a time. 
Your Admin creds you should know as you use them in the Portal to logon there. 
Then set the v3 creds and then use the Test-IdentityNowCredentials cmdlet to verify.
Then generate a new PAT (using a new/unique name) and test again with Test-IdentityNowCredentials.
When working save the config. You don't need v2 for any of the functions. v2 is only for generating new auth for a VA.

**Comment by jiggle-1** [comment]
Hey Darren -

Thanks for the response. I very much appreciate it. This is in a more complex environment (3 AD's) that's in the midst of a spin-off so it's hard for us to keep accounts straight. I think Sailpoint transforms have muddied the waters at least in our SB environment so I'm not 100% sure on that password.

I can get an access token from Sailpoint Prod using another ps script that is not using un and pw. Is it possible to use your module/sailpoint with just an access token? 

Thanks again!

**Comment by darrenjrobinson** [comment]
You could try setting your v3 creds you've obtained elsewhere into your config and validating them.
Then generate a Personal Access Token and you should be in action.

**Comment by jiggle-1** [comment]
Hey Darren -

Thanks for the suggestions and thanks for publishing this module. We appreciate the work.

Thanks,
Stephen

**Comment by jiggle-1** [comment]
Hey guys -

Thanks again for helping me with this.

I think the issue with my account is that its authoritative source is a SAP file. I tried to Francken-script the access token to the same variable that the Sailpoint PowerShell module is setting. 

**Auth input**
$url=''
$v3Creds = [pscredential]::new($clientIDv3, ($clientSecretv3 | ConvertTo-SecureString -AsPlainText -Force))
$postdata= @{client_id='';client_secret='';grant_type='client_credentials'}
$content='application/x-www-form-urlencoded'
$v3Token=Invoke-RestMethod -URI $url -Method Post -Body $postdata -ContentType $content 
Write-Host $v3Token

Set-IdentityNowCredential -v3APIKey $v3Creds

$orgName = ""
Set-IdentityNowOrg -orgName $orgName

**Output:**
Search-IdentityNowUserProfile : Bad Query. Check your query. The remote server returned an error: (401) Unauthorized.
At line:36 char:10
+ $owner = Search-IdentityNowUserProfile 

Do you guys have any suggestions or advice?

Thanks,

**Comment by darrenjrobinson** [comment]
Stephen, there is still a problem with your credentials (401 Unauthorized).
After setting your v3 Creds, validate they are correct using the Test-IdentityNowCredentials cmdlet. 

Do you have another account on another source that is an Admin (like the default SailPoint Admins flatfile source) that you can try to use instead of the account associated with the SAP Source?.

**Comment by jiggle-1** [comment]
Hey Darren -

Thanks for the idea. I will give it a shot and I am asking a couple of other admins test if the creds will work for them.

Thanks again!

**Comment by jiggle-1** [comment]
Hey -

My auth issue was resolved by creating a local API user and generating the keys from within that account.

Thanks again for the help!

**Comment by darrenjrobinson** [comment]
Fantastic, thx for the update Stephen. 
Great to hear you have it working now.
