### ISSUE TITLE
Auth error: Admin credentials

### ISSUE THREAD

**Issue by demongp** [darrenjrobinson/powershell_module_identitynow#4]
I struggled a bit to get authenticated.

I think its because we do not allow a repeat of the password as a MFA option.

I created a new user (in our test tenant of course!), and configured it to allow a repeat of the password as a MFA option, and I could succesfully authenticate and use the cmdlets.

I know the authentication methods are very weird and hard to understand, but is there a way to allow access by not enabling the "retype password" for MFA option?

**Comment by darrenjrobinson** [comment]
I have this configured on a number of different Org's with different Strong Auth configurations. They aren't triggered as long as the account you are using exists with a password in IdentityNow. 

The only time I'd expect you to be triggered/fail authN would be if the account you are using is configured on a Source that is configured for Federated AuthN to an IDP (e.g Active Directory with Conditional Auth). 

Try using an account on the SailPoint IdentityNow configured Identity Admins Source (Flat File) that has the Admin Role assigned.
