### ISSUE TITLE
IdentityNow Profiles Report

### ISSUE THREAD

**Issue by bama19942000** [darrenjrobinson/powershell_module_identitynow#41]
The report does not include all the values for attributes that have transforms. Is there a way to modify the report so that it includes the full set of data including the transform and or rule name?

**Comment by darrenjrobinson** [comment]
Can you please provide more information of the output you're seeing and what you are expecting so I can recreate and look further into it?

**Comment by bama19942000** [comment]
![image](https://user-images.githubusercontent.com/50209840/123103081-4a326200-d3fb-11eb-9bd0-6ec5b96b5401.png)

The attributes that do not have source or source attributes columns populated have transforms attached to them. This seems to be consistent with any IDN profile I look at.

**Comment by darrenjrobinson** [comment]
How does something like this look?? 

![image](https://user-images.githubusercontent.com/384733/124843725-e781be80-dfd5-11eb-8da1-cc88023b508c.png)

**Comment by darrenjrobinson** [comment]
@bama19942000 please test New-IdentityNowIdentityProfilesReport from the v1.1.5 branch. 

https://github.com/darrenjrobinson/powershell_module_identitynow/commit/47843beef74d7b59fde9b2aa79f6ef737024b2b1

**Comment by bama19942000** [comment]
That's awesome I will give it a go!

**Comment by bama19942000** [comment]
This format provides a lot of value now. Thanks for digging in.
