### ISSUE TITLE
Authentication Issues using PowerShell Core and Linux OS

### ISSUE THREAD

**Issue by jmilczek** [darrenjrobinson/powershell_module_identitynow#64]
Even though I have set AdminCredential, v2APIKEY and v3APIKEY credentials using the Set-IdentityNowCredential cmdlet, I receive an error when attempting to run any of the SailpointIdentityNow module's cmdlets that require authentication. This is not an issue if I run the same commands using the same credentials on PowerShell 5.1 Desktop, PowerShell 6 Core or PowerShell 7 Core on a Windows system.
```powershell

Get-Host

Name             : Visual Studio Code Host
Version          : 2023.6.0
InstanceId       : 697f6a26-215d-4bee-86bf-fc40899a3c10
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Linux 5.19.0-43-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Get-Module SailPointIdentityNow          

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     1.1.6                 SailPointIdentityNow                {Complete-IdentityNowTask, Convert-UnixTime, Export-IdentityNowConfig, Get-HashString…}

$adminCreds.GetType()          

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     PSCredential                             System.Object

$v2Creds.GetType()   

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     PSCredential                             System.Object

$v3Creds.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     PSCredential                             System.Object

#region Populate Sailpoint Configuration
Set-IdentityNowOrg -orgName $idnorgname

# IdentityNow Admin User
$adminCreds = [pscredential]::new((Get-AzKeyVaultSecret -VaultName $azkvname -Name $kvidnadminusername -AsPlainText), (Get-AzKeyVaultSecret -VaultName $azkvname -Name $kvidnadminpassword).SecretValue)

# IdentityNow v2 API Creds
$v2Creds = [pscredential]::new((Get-AzKeyVaultSecret -VaultName $azkvname -Name $kvidnv2username -AsPlainText), (Get-AzKeyVaultSecret -VaultName $azkvname -Name $kvidnv2password).SecretValue)

# IdentityNow v3 API Creds
$v3Creds = [pscredential]::new((Get-AzKeyVaultSecret -VaultName $azkvname -Name $kvidnv3username -AsPlainText), (Get-AzKeyVaultSecret -VaultName $azkvname -Name $kvidnv3password).SecretValue)

Set-IdentityNowCredential -AdminCredential $adminCreds -v2APIKey $v2Creds -v3APIKey $v3Creds -Verbose

Get-SCWXIdentityNowAccessProfile -Verbose
Unable to auth password grant type for ########## v2:True v3:True cred:True pat:False {"error":"unauthorized","error_description":"Full authentication is required to access this resource"}

Test-IdentityNowCredentials -Verbose
VERBOSE: AuthType: Admin Creds
VERBOSE: {
  "grant_type": "password",
  "username": "############",
  "password": "##################################################"
}
VERBOSE: HTTP/1.1 POST with 115-byte payload
VERBOSE: received 102-byte response of content type application/json
WARNING: Testing APIv3 credentials failed for ######### Unable to continue.
WARNING: Unable to auth password grant type for ######### v2:True v3:True cred:True pat:False {"error":"unauthorized","error_description":"Full authentication is required to access this resource"}

```

**Comment by darrenjrobinson** [comment]
This maybe associated with SailPoint AuthN API changes.
Create a Personal Access Token in the Admin Portal for your account and set
that in your module creds config.
The module will use that as priority.

DR

**Comment by jmilczek** [comment]
But why does it work on a Windows OS?Sent from my iPhoneOn Jun 16, 2023, at 6:17 PM, Darren Robinson ***@***.***> wrote:﻿
This maybe associated with SailPoint AuthN API changes.

Create a Personal Access Token in the Admin Portal for your account and set

that in your module creds config.

The module will use that as priority.



DR

**Comment by darrenjrobinson** [comment]
I’ve definitely used the module on Linux in cloud automation scenarios.
However the local saving of the configuration and autoload is a Windows
only feature.
In cloud automation I pull the creds and keys from a PaaS KeyVault and set
them and the org before using module cmdlets.

Is this your scenario? Persistence between sessions?

**Comment by jmilczek** [comment]
I have it working in the same scenario. Works in Azure Automation pulling creds from Azure Keyvault; doesn’t work in Azure Functions.I’m not sure if you realize that Azure Automation with the PowerShell Core runtime is still running on Windows.Azure Functions with PowerShell Core is running on Linux.Try running your module on an actual Linux operating system and you’ll see what I’m talking about. Sent from my iPhoneOn Jun 18, 2023, at 6:09 AM, Darren Robinson ***@***.***> wrote:﻿
I’ve definitely used the module on Linux in cloud automation scenarios.

However the local saving of the configuration and autoload is a Windows

only feature.

In cloud automation I pull the creds and keys from a PaaS KeyVault and set

them and the org before using module cmdlets.



Is this your scenario? Persistence between sessions?

**Comment by jmilczek** [comment]
Darren,

This is the problem. This line from Get-IdentityNowAuth does not convert
the secure string to plain text like it does on a Windows host:

[System.Runtime.InteropServices.marshal]::PtrToStringAuto([System.Runtime.InteropServices.marshal]::SecureStringToBSTR($IdentityNowConfiguration.AdminCredential.Password))

-Jason

**Comment by jmilczek** [comment]
This seems to work:

[System.Runtime.InteropServices.marshal]::*PtrToStringBSTR*
([System.Runtime.InteropServices.marshal]::SecureStringToBSTR($IdentityNowConfiguration.AdminCredential.Password))

Source: https://github.com/PowerShell/PowerShell/issues/13494

I'm happy to check out a branch and fix it, but I'm not sure what to do
about signing. Like, do I sign with my cert or take the signing block out
all together? Let me know how you want to handle it.

-Jason
