### ISSUE TITLE
Search-IdentityNowEntitlements not working as expected

### ISSUE THREAD

**Issue by dmcconnell68** [darrenjrobinson/powershell_module_identitynow#70]
Hi, can you tell me why this would not work?

Search-IdentityNowEntitlements -Query "displayName:Okta-AWS-123456789012-role1", have also tried "name:Okta-AWS-123456789012-role1"

When I run it, it just seems to start returning all entitlements, certainly not the one I'm looking for.

This seems to work fine, but I won't have the ID, that's what I'm trying to get for a specific group:
Search-IdentityNowEntitlements -query "id:718459e8102b40fda692094a478f7aba"
and this works:  Search-IdentityNowEntitlements -query "718459e8102b40fda692094a478f7aba"

Thanks,
David

**Comment by darrenjrobinson** [comment]
Hi David,

My recommendation to get the correct syntax for your scenario is to get the
search working in the IDN portal. Use F12 (browser dev tools) to look at
what it sends to the entitlements API (network tab in Dev Tools) and the
post/payload section.
That will point you in the right direction.

Cheers
DR
