### ISSUE TITLE
No Path for Save-IdentityNowConfiguration

### ISSUE THREAD

**Issue by alvatraz** [darrenjrobinson/powershell_module_identitynow#9]
Looking to work on your PS module for IDN (referenced here: https://blog.darrenjrobinson.com/sailpoint-identitynow-powershell-module/)
Trying to save the beginning code section and output gives this error:
Export-Clixml : Cannot bind argument to parameter 'Path' because it is null.
At /Users/aalvarez/.local/share/powershell/Modules/SailPointIdentityNow/1.0.5/scripts/Save-IdentityNowConfiguration.ps1:28 char:25
+     Export-Clixml -Path $IdentityNowConfigurationFile -InputObject $I ...
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Export-Clixml], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ExportClixmlCommand

**Comment by darrenjrobinson** [comment]
When the Module Loads it looks for a configuration file name IdentityNowConfiguration.clixml in the $env:LOCALAPPDATA directory.
When saving a config it saves/creates the IdentityNowConfiguration.clixml file in the $env:LOCALAPPDATA directory. 
In your PowerShell session what does $env:LOCALAPPDATA resolve to?
It should default to something like C:\Users\Username\AppData\Local
Make sure the environment variable $env:LOCALAPPDATA, path and permissions are correct.
